- hosts: win
  gather_facts: false
  vars:
    user_ansible: test_ansible
    __password_ansible: 'Welcome-1'
  tasks:
    - name: Do Setup
      setup:

    - name: "New User Creation -- {{ user_ansible }}"
      win_user:
        account_disabled: false
        account_locked: false
        description: New User for Ansible
        fullname: "Ansible User"
        groups: "Administrators"
        groups_action: add
        name: "{{ user_ansible }}"
        password: "{{ __password_ansible }}"
        password_expired: false
        password_never_expires: true
        state: present

    - name: "Create a profile for {{ user_ansible }}"
      win_user_profile:
        username: "{{ user_ansible }}"
        state: present

    - name: Make Sure Temp directory exist
      win_file:
        path: "{{ item }}"
        state: directory
      loop:
        - "C:\\temp\\{{ user_ansible }}\\scripts"
        - "C:\\temp\\{{ user_ansible }}\\certs"


    - name: Copy public key for thumbprint
      win_copy:
        src: "{{ new_certificate_pub_key_file }}"
        dest: "C:\\temp\\{{ user_ansible }}\\certs\\cert.pem"


    - name: Copy Powershell Script
      win_template:
        src: client_cert_attachment.ps1.j2
        dest: "C:\\temp\\{{ user_ansible }}\\scripts\\client_cert_attachment.ps1"
      vars:
        cert_path: "C:\\temp\\{{ user_ansible }}\\certs\\cert.pem"


    - name: Execute Powershell Script
      win_shell: "powershell C:\\temp\\{{ user_ansible }}\\scripts\\client_cert_attachment.ps1"
#      register: output

#    - debug:
#        var: output

    - name: Cleanup
      win_file:
        path: "C:\\temp\\{{ user_ansible }}"
        state: absent
#      register: cleanup_stat
#      until: cleanup_stat.failed == False
#      retries: 10
#      delay: 5
#      ignore_errors: true



