- hosts: win
  gather_facts: false
  vars:
    user_ansible: test_ansible
  tasks:
    - name: Do Setup
      setup:

    - name: Makesure Directories Exist..
      win_file:
        path: "C:\\temp\\__tmp_update_scripts"
        state: directory

    - name: Copy Public Key
      win_copy:
        src: "{{ new_certificate_pub_key_file }}"
        dest: "C:\\temp\\__tmp_update_scripts\\cert.pem"

    - name: Copy Certificate storing scripts
      win_template:
        src: add_cert_to_store.ps1.j2
        dest: "C:\\temp\\__tmp_update_scripts\\add_cert_to_store_{{ item }}.ps1"
      loop:
        - 'Root'
        - 'TrustedPeople'
      vars:
        cert_path: "C:\\temp\\__tmp_update_scripts\\cert.pem"

    - name: Adding certificates to store
      win_shell: "powershell C:\\temp\\__tmp_update_scripts\\add_cert_to_store_{{ item }}.ps1"
      loop:
        - 'Root'
        - 'TrustedPeople'

    - name: Cleanup
      win_file:
        path:  "C:\\temp\\__tmp_update_scripts"
        state: absent

